# Generated by Django 4.1.5 on 2023-01-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipgenerate',
            name='valor',
            field=models.IntegerField(unique=True),
        ),
    ]
